[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = ["dotnet publish BigLineconnect.Relay/BigLineconnect.Relay.csproj -c Release -o /app/out"]

[start]
cmd = "dotnet /app/out/BigLineconnect.Relay.dll"
