DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql += 'SELECT ''' + TABLE_NAME + ''' AS TableName, count(*) as c FROM ' + TABLE_NAME + ' WHERE ' + COLUMN_NAME + ' = ''' + '2BE087D7-3C30-42CE-B402-9BB9F7977CC0' + '''; '
FROM INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE = 'uniqueidentifier' AND TABLE_NAME NOT LIKE 'sys%' AND TABLE_NAME NOT LIKE 'spt_%';
EXEC(@sql);