<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>false</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>

    <AssemblyName>BigLineconnect_setup</AssemblyName>
    <AssemblyTitle>BigLineconnect Setup Installer</AssemblyTitle>
    <Product>BigLineconnect Uzaktan Masaüstü Kurulumu</Product>
    <Company>BIGLINE AS</Company>
    <Authors>BIGLINE</Authors>
    <Copyright>Copyright © 2026 BIGLINE AS</Copyright>
    <AssemblyVersion>17.0.0.0</AssemblyVersion>
    <FileVersion>17.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\BigLineconnect.exe">
      <LogicalName>BigLineconnect.exe</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\BigLineTransfer.exe">
      <LogicalName>BigLineTransfer.exe</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\icon.ico">
      <LogicalName>icon.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\LisansOlustur.ps1">
      <LogicalName>LisansOlustur.ps1</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\company.txt" Condition="Exists('Resources\company.txt')">
      <LogicalName>company.txt</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
