<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>false</PublishAot>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>BigLineconnect</AssemblyName>
    <Version>3.30.27</Version>
    <AssemblyVersion>3.30.27.0</AssemblyVersion>
    <FileVersion>3.30.27.0</FileVersion>
    <ProductVersion>v3.30.27</ProductVersion>
    <Authors>BIGUS BILISIM GELISTIRME VE UYGULAMA SISTEMLERI LIMITED SIRKETI</Authors>
    <Company>BIGUS BILISIM GELISTIRME VE UYGULAMA SISTEMLERI LIMITED SIRKETI</Company>
    <Product>BigLineconnect Kurumsal Uzaktan Masaustu ve Destek Yazilimi</Product>
    <Copyright>Copyright (c) 2026 BIGUS BILISIM GELISTIRME VE UYGULAMA SISTEMLERI LIMITED SIRKETI. Tum Haklari Saklidir.</Copyright>
    <Description>BigLineconnect Kurumsal Uzaktan Masaustu Baglantisi ve Destek Yazilimi</Description>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="9.0.0" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\**" Exclude="wwwroot\*.exe;wwwroot\*.zip;wwwroot\*.pdb;wwwroot\*.bak" />
    <None Update="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
