//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bigus.Aktarici.Linq.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AZIZE\\TUGI;Initial Catalog=MikroDB_V12_OTOCAM;Integrated Security=Tru" +
            "e")]
        public string MikroDB_V12_OTOCAMConnectionString {
            get {
                return ((string)(this["MikroDB_V12_OTOCAMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AZIZE\\TUGI;Initial Catalog=MikroDB_V12_YAMI;Integrated Security=True")]
        public string MikroDB_V12_YAMIConnectionString {
            get {
                return ((string)(this["MikroDB_V12_YAMIConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AZIZE\\TUGI;Initial Catalog=MikroDB_V12_MARSDEMO;Integrated Security=T" +
            "rue")]
        public string MikroDB_V12_MARSDEMOConnectionString {
            get {
                return ((string)(this["MikroDB_V12_MARSDEMOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AZIZE\\TUGI;Initial Catalog=MikroDB_V12_ADISYON;User ID=sa;Password=32" +
            "5382")]
        public string MikroDB_V12_ADISYONConnectionString {
            get {
                return ((string)(this["MikroDB_V12_ADISYONConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BSERVER;Initial Catalog=MikroDB_V12_ENGINLER;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=1907")]
        public string MikroDB_V12_ENGINLERConnectionString {
            get {
                return ((string)(this["MikroDB_V12_ENGINLERConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP;Initial Catalog=MikroDB_V12;Integrated Security=True")]
        public string MikroDB_V12ConnectionString {
            get {
                return ((string)(this["MikroDB_V12ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BSERVER;Initial Catalog=MikroDB_V14_BULGARIA;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=1907")]
        public string MikroDB_V14_BULGARIAConnectionString {
            get {
                return ((string)(this["MikroDB_V14_BULGARIAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BSERVER;Initial Catalog=MikroDB_V14;Persist Security Info=True;User I" +
            "D=sa;Password=1907")]
        public string MikroDB_V14ConnectionString {
            get {
                return ((string)(this["MikroDB_V14ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BSERVER;Initial Catalog=MikroDB_V14_COZUM;Persist Security Info=True;" +
            "User ID=sa;Password=1907")]
        public string MikroDB_V14_COZUMConnectionString {
            get {
                return ((string)(this["MikroDB_V14_COZUMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CHT;Initial Catalog=MikroDB_V14_KAYNAK;Integrated Security=True")]
        public string MikroDB_V14_KAYNAKConnectionString {
            get {
                return ((string)(this["MikroDB_V14_KAYNAKConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CHT;Initial Catalog=MikroDB_V14_CHT;Integrated Security=True")]
        public string MikroDB_V14_CHTConnectionString {
            get {
                return ((string)(this["MikroDB_V14_CHTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CHT;Initial Catalog=MikroDB_V14;Integrated Security=True")]
        public string MikroDB_V14ConnectionString1 {
            get {
                return ((string)(this["MikroDB_V14ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=cht\\ms2008;Initial Catalog=MikroDB_V14;Integrated Security=True")]
        public string MikroDB_V14ConnectionString2 {
            get {
                return ((string)(this["MikroDB_V14ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XARAPC\\SQLEXPRESS;Initial Catalog=MikroDB_V15_DEMO;Integrated Securit" +
            "y=True")]
        public string MikroDB_V15_DEMOConnectionString {
            get {
                return ((string)(this["MikroDB_V15_DEMOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008R2EX;Initial Catalog=MikroDB_V15_REST;Integrated Secur" +
            "ity=True")]
        public string MikroDB_V15_RESTConnectionString {
            get {
                return ((string)(this["MikroDB_V15_RESTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=MikroDB_V15_V15_YENI_EXE;Integrated Security=True")]
        public string MikroDB_V15_V15_YENI_EXEConnectionString {
            get {
                return ((string)(this["MikroDB_V15_V15_YENI_EXEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V15_1512a;Integrated Security" +
            "=True")]
        public string MikroDB_V15_1512aConnectionString {
            get {
                return ((string)(this["MikroDB_V15_1512aConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=MikroDB_V16_Kaynak;Integrated Security=True")]
        public string MikroDB_V15_DEMOConnectionString1 {
            get {
                return ((string)(this["MikroDB_V15_DEMOConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V15;Integrated Security=True")]
        public string MikroDB_V15ConnectionString {
            get {
                return ((string)(this["MikroDB_V15ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V16;Integrated Security=True")]
        public string MikroDB_V16ConnectionString {
            get {
                return ((string)(this["MikroDB_V16ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V16_Kaynak6;Integrated Securi" +
            "ty=True")]
        public string MikroDB_V16_Kaynak6ConnectionString {
            get {
                return ((string)(this["MikroDB_V16_Kaynak6ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQL2008;Initial Catalog=MikroDB_V16_db;Integrated Security=True")]
        public string MikroDB_V16_dbConnectionString {
            get {
                return ((string)(this["MikroDB_V16_dbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V16_17b;Integrated Security=T" +
            "rue")]
        public string MikroDB_V16_17bConnectionString {
            get {
                return ((string)(this["MikroDB_V16_17bConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V16_17c;Integrated Security=T" +
            "rue")]
        public string MikroDB_V16_17cConnectionString {
            get {
                return ((string)(this["MikroDB_V16_17cConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V16_19b;Integrated Security=T" +
            "rue")]
        public string MikroDB_V16_19bConnectionString {
            get {
                return ((string)(this["MikroDB_V16_19bConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V16_19c;Integrated Security=T" +
            "rue")]
        public string MikroDB_V16_19cConnectionString {
            get {
                return ((string)(this["MikroDB_V16_19cConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V16_21d;Integrated Security=T" +
            "rue")]
        public string MikroDB_V16_21dConnectionString {
            get {
                return ((string)(this["MikroDB_V16_21dConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SANALPC\\SQL2008;Initial Catalog=MikroDB_V16_27a;Integrated Security=T" +
            "rue")]
        public string MikroDB_V16_27aConnectionString {
            get {
                return ((string)(this["MikroDB_V16_27aConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MEHMET;Initial Catalog=MikroDB_V16_BAL23;Persist Security Info=True;U" +
            "ser ID=emfyazilim;Password=14531453")]
        public string MikroDB_V16_BAL23ConnectionString {
            get {
                return ((string)(this["MikroDB_V16_BAL23ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MEHMET;Initial Catalog=MikroDesktop_EMFSOFT;Integrated Security=True;" +
            "Encrypt=True;TrustServerCertificate=True")]
        public string MikroDesktop_EMFSOFTConnectionString {
            get {
                return ((string)(this["MikroDesktop_EMFSOFTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mikrocozumortagi.com;Initial Catalog=MikroDesktop_EMFSOFT;User ID=emf" +
            "yazilim;Password=Emf145382;TrustServerCertificate=True")]
        public string MikroDesktop_EMFSOFTConnectionString1 {
            get {
                return ((string)(this["MikroDesktop_EMFSOFTConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MYLENOVO;Initial Catalog=MikroDesktop_MAHMUT;Integrated Security=True" +
            ";TrustServerCertificate=True")]
        public string MikroDesktop_MAHMUTConnectionString {
            get {
                return ((string)(this["MikroDesktop_MAHMUTConnectionString"]));
            }
        }
    }
}
